language: ruby
cache: bundler
rvm:
  - 2.0.0
bundler_args: --without development
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database samsa_website_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec spec
notifications:
  email: false
